---
- name: One Million Files
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: File Creation
      shell: touch /tmp/file{{ item }}.txt; sleep 5
      register: result
      with_sequence: count=1000000

    - debug: var=result
